// Data Export Utilities
// Sprint 3 Task 5.2: Export functionality for admin data

import { format } from 'date-fns';

/**
 * Converts JSON data to CSV format
 */
export function jsonToCSV(data: any[], headers?: string[]): string {
    if (data.length === 0) return '';

    // Auto-detect headers from first object if not provided
    const csvHeaders = headers || Object.keys(data[0]);

    // Create header row
    const headerRow = csvHeaders.join(',');

    // Create data rows
    const dataRows = data.map(row => {
        return csvHeaders.map(header => {
            const value = row[header];

            // Handle null/undefined
            if (value === null || value === undefined) return '';

            // Escape commas and quotes
            const stringValue = String(value);
            if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
                return `"${stringValue.replace(/"/g, '""')}"`;
            }

            return stringValue;
        }).join(',');
    });

    return [headerRow, ...dataRows].join('\n');
}

/**
 * Download a string as a file
 */
export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Export WOD schedule to CSV
 */
export interface WODExportData {
    date: string;
    title: string;
    description: string;
    type: string;
    video_url?: string;
}

export function exportWODSchedule(wods: WODExportData[]): void {
    const csv = jsonToCSV(wods, ['date', 'title', 'type', 'description', 'video_url']);
    const filename = `wod-schedule-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    downloadFile(csv, filename, 'text/csv');
}

/**
 * Export participant data to CSV
 */
export interface ParticipantExportData {
    full_name: string;
    total_points: number;
    status: string;
    created_at: string;
}

export function exportParticipants(participants: ParticipantExportData[]): void {
    const csv = jsonToCSV(participants, ['full_name', 'total_points', 'status', 'created_at']);
    const filename = `participants-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    downloadFile(csv, filename, 'text/csv');
}

/**
 * Export leaderboard to CSV
 */
export interface LeaderboardExportData {
    rank: number;
    name: string;
    squad: string;
    points: number;
}

export function exportLeaderboard(leaderboard: LeaderboardExportData[]): void {
    const csv = jsonToCSV(leaderboard, ['rank', 'name', 'squad', 'points']);
    const filename = `leaderboard-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    downloadFile(csv, filename, 'text/csv');
}

/**
 * Export daily logs for analytics
 */
export interface DailyLogExportData {
    date: string;
    user_name: string;
    wod_done: boolean;
    steps_done: boolean;
    water_done: boolean;
    sleep_done: boolean;
    clean_eating_done: boolean;
    daily_points: number;
}

export function exportDailyLogs(logs: DailyLogExportData[]): void {
    const csv = jsonToCSV(logs);
    const filename = `daily-logs-${format(new Date(), 'yyyy-MM-dd')}.csv`;
    downloadFile(csv, filename, 'text/csv');
}

/**
 * Create text-based simple report (for quick copy-paste)
 */
export function generateTextReport(data: {
    totalParticipants: number;
    totalWods: number;
    avgCompletionRate: number;
    topSquad: string;
    dateRange: string;
}): string {
    return `
GET FIT TOGETHER - ADMIN REPORT
Generated: ${format(new Date(), 'PPP')}
Date Range: ${data.dateRange}

═══════════════════════════════════════════

📊 KEY METRICS:
   • Total Participants: ${data.totalParticipants}
   • Total WODs Deployed: ${data.totalWods}
   • Avg Completion Rate: ${data.avgCompletionRate.toFixed(1)}%
   • Top Performing Squad: ${data.topSquad}

═══════════════════════════════════════════

Report generated by Get Fit Together Admin Portal
    `.trim();
}
